#!/usr/bin/env bash
#Bash script that displays Best School 10 times; used while loop
#on 9 also print hi
x=1
while [ $x -le 10 ]
do
    echo "Best School"
    if((x == 9))
    then
	echo "Hi"
    fi
    ((x++))
done
