#!/usr/bin/env bash
#Write a Bash script that displays the time for 12 hours and 59 minutes:
#display hours from 0 to 12
#display minutes from 1 to 59
#You must use the while loop (for and until are forbidden)
x=0
while [ $x -le 12 ]
do
    echo "Hour: "$x
    y=1
    while [ $y -le 59 ]
    do
	echo $y
	((y++))
    done
    ((x++))
done
